Importar Biblioteca Numpy

In [1]:
import numpy as np

Várias formas de criar array

In [2]:
array = np.arange(15)

In [3]:
array

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [5]:
array = array.reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
array.shape

(3, 5)

In [7]:
type(array)

numpy.ndarray

In [8]:
array = np.array([1,2,3])

array

array([1, 2, 3])

In [10]:
array = np.array([(1,2,3),(4,5,6)])

array

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
array = np.zeros((3,3))

array

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
array = np.zeros((3,3,2))

array

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [14]:
array = np.arange(2,10,2)

array

array([2, 4, 6, 8])

In [17]:
array = np.linspace(0,2,9)
array

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])

In [18]:
array = np.linspace(0,1,18)
array

array([0.        , 0.05882353, 0.11764706, 0.17647059, 0.23529412,
       0.29411765, 0.35294118, 0.41176471, 0.47058824, 0.52941176,
       0.58823529, 0.64705882, 0.70588235, 0.76470588, 0.82352941,
       0.88235294, 0.94117647, 1.        ])

Operações Básicas com Arrays

In [19]:
#criar dois array
x = np.array([2,4,6,8,10,12])
y = np.arange(6)
y

array([0, 1, 2, 3, 4, 5])

In [20]:
#soma de array
z = x + y
z

array([ 2,  5,  8, 11, 14, 17])

In [21]:
#subtração
z = x - y
z

array([2, 3, 4, 5, 6, 7])

In [22]:
#Multiplicação
z = x * y
z

array([ 0,  4, 12, 24, 40, 60])

In [23]:
#potência
z = x ** y
z

array([     1,      4,     36,    512,  10000, 248832], dtype=int32)

In [25]:
#teste lógico diretamente na array
x>2

array([False,  True,  True,  True,  True,  True])

In [29]:
#Soma
x.sum()


42

In [30]:
y.sum()

15

In [31]:
x.max()

12

In [32]:
y.max()

5

In [33]:
x.min()

2

In [34]:
y.min()

0

In [35]:
array = np.array([(1,2,3),(4,5,6)])

array

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
array.sum(axis=0) #soma linhas

array([5, 7, 9])

In [39]:
array.sum(axis=1) #soma colunas

array([ 6, 15])

In [40]:
x[3]

8

In [41]:
y[4]

4

In [42]:
#mostrando a partir da posição 2 até o final
x[2:]

array([ 6,  8, 10, 12])

In [43]:
#último elemento da array
x[-1]

12

In [45]:
#intervalo de elementos pelo indice da array
x[2:5]

array([ 6,  8, 10])

In [46]:

array

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
#todos das linhas da 2ª coluna

array[0:2,1]

array([2, 5])

In [48]:
#duas primeiras posições da primeira linha
array[0,:2]


array([1, 2])

In [49]:
#última posição da última linha
array[1,-1]

6

In [53]:
#duas colunas iniciais e duas colunas finais
array[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [54]:
array.T

array([[1, 4],
       [2, 5],
       [3, 6]])